pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                dir('backend') { // Change working directory to backend
                    sh 'docker build -t my-mern-app:v1 .'
                }
            }
        }
    }
}

